dist: trusty
sudo: required
language: node_js
notifications:
  email: false
node_js: '8'

install:
  - npm i
  - pip install awscli --upgrade --user

script:
  - npm run build
  - aws s3 rm s3://lexy.sheaclose.com --recursive
  - aws s3 cp ./build/ s3://lexy.sheaclose.com/ --recursive
  - aws cloudfront create-invalidation --distribution-id E3JTQA8C7AV3WE --paths /*
